Add support of OIDC provider autodiscovery
maicol07/laravel-oidc-client pull request #2
Opened 2022-01-18 15:29 UTC by eviweb

This commit adds autodiscovery support.
If the `OIDC_PROVIDER_URL` environment variable is set and is valid, the
returned settings are automatically merged with the package configuration.
This is a convenient way to avoid the need to configure everything
manually.
In the cases where this variable is not set or the provided URL is not
valid, then we stay in the current functioning.

Signed-off-by: Eric Villard <dev@eviweb.fr>

2022-01-18 15:49 UTC, maicol07 requested changes
Thank you for your PR! I've left a comment regarding the GET request to the OIDC discovery endpoint

2022-01-18 15:49 UTC, maicol07 commented on src/OIDCServiceProvider.php
> +            $config = Http::get($providerURL)->json();
This isn't optimal. You should check if the request were successfull and handle the error: https://laravel.com/docs/8.x/http-client#error-handling

2022-01-18 15:49 UTC, maicol07 commented on src/OIDCServiceProvider.php
> +            $config = Http::get($providerURL)->json();
Also, you should set the url to `PROVIDER_URL/.well-known/openid_configuration`, as stated by the official specs: https://openid.net/specs/openid-connect-discovery-1_0.html#ProviderConfigurationRequest

2022-01-18 15:55 UTC, eviweb commented
Hi @maicol07,
I just see that the autodiscovery is implemented in the `Maicol07\OpenIDConnect\Client` class.
Unfortunately something goes wrong and throws this error [https://flareapp.io/share/J7ovM0kP](https://flareapp.io/share/J7ovM0kP)

2022-01-18 16:03 UTC, maicol07 commented
@eviweb yes, I remebered OIDC Discovery was already implemented, since I use it too. It might be caused by the default value of the settings, since user endpoints overwrites the OIDC discovery ones. I'll fix it now

2022-01-18 16:17 UTC, eviweb commented
> @eviweb yes, I remebered OIDC Discovery was already implemented, since I use it too. It might be caused by the default value of the settings, since user endpoints overwrites the OIDC discovery ones. I'll fix it now

@maicol07, for me the problem comes from here [https://github.com/maicol07/oidc-client-php/blob/deeec3d8e053cc2bc42ed696189c0f3b33ad1499/src/Client.php#L127](https://github.com/maicol07/oidc-client-php/blob/deeec3d8e053cc2bc42ed696189c0f3b33ad1499/src/Client.php#L127).

The autodiscovery link provided by my OIDC provider already contains the `/.well-known/openid-configuration`.
As it is concatenated by default in the client, the autodiscovery URL was no more correct.
Maybe this part should be added only if not present.
What do you think of it ?

2022-01-18 16:20 UTC, maicol07 commented
I've fixed it now in the client. Can you try to update the client to its `@dev` version?

2022-01-18 17:07 UTC, eviweb commented
> I've fixed it now in the client. Can you try to update the client to its `@dev` version?

@maicol07,
reproducing the previous error, the fix is never reached as the autodiscovery request fails.
The error is thrown here [https://github.com/maicol07/oidc-client-php/blob/7f902e17f3b2523f1fd12cdc4cfeced79a942b58/src/Client.php#L166](https://github.com/maicol07/oidc-client-php/blob/7f902e17f3b2523f1fd12cdc4cfeced79a942b58/src/Client.php#L166).

2022-01-18 17:13 UTC, maicol07 commented
@eviweb the autodiscovery request is done earlier: [https://github.com/maicol07/oidc-client-php/blob/7f902e17f3b2523f1fd12cdc4cfeced79a942b58/src/Client.php#L126](https://github.com/maicol07/oidc-client-php/blob/7f902e17f3b2523f1fd12cdc4cfeced79a942b58/src/Client.php#L126)

What is your OIDC provider? It must be the plain URL without `.well-known/oidc-configuration`. 

Example: Google has an OIDC provider with this discovery endpoint: [https://accounts.google.com/.well-known/openid-configuration.](https://accounts.google.com/.well-known/openid-configuration.) You must then set the `PROVIDER_URL` to `https://accounts.google.com`

2022-01-18 17:26 UTC, eviweb commented
> @eviweb the autodiscovery request is done earlier: https://github.com/maicol07/oidc-client-php/blob/7f902e17f3b2523f1fd12cdc4cfeced79a942b58/src/Client.php#L126
> 
> What is your OIDC provider? It must be the plain URL without `.well-known/oidc-configuration`. 
> 
> Example: Google has an OIDC provider with this discovery endpoint: https://accounts.google.com/.well-known/openid-configuration. You must then set the `PROVIDER_URL` to `https://accounts.google.com`

Azure AD.
As I said before, the value of `OIDC_PROVIDER_URL` I configured previously, was including the part `/.well-known/openid-configuration` which caused the error.
Removing it, solved the issue.
I admit that I'm new to oidc autodiscovery, but I think I won't be the only one to make this mistake.
If the client appends the suffix `/.well-known/openid-configuration` only if not present, I think it will provide a better user experience.
At least, adding a notice in this package README would be welcome.
Regarding Azure AD there is a very annoying issue, I will open a ticket for this.
I think we can close this PR without merging.

2022-01-18 17:31 UTC, maicol07 commented
> If the client appends the suffix `/.well-known/openid-configuration` only if not present, I think it will provide a better user experience.

I agree. I'm going to fix this now in the client.

> At least, adding a notice in this package README would be welcome.

Since I change it in the client, I don't think this will be necessary anymore.

> I think we can close this PR without merging.

Closing...

2022-01-18 17:31 UTC, closed without merging

2022-01-18 17:44 UTC, maicol07 commented
@eviweb done! Check the commit above

2022-01-19 07:38 UTC, eviweb commented
> @eviweb done! Check the commit above

hi @maicol07,
many thanks for your reactivity and your job in its whole.